compatibility_date = "2022-12-27"

name = "homeair"
account_id = "c6a05dacf1861c2fc26e676732f094d1"
main = "workers-site/index.ts"

[site]
bucket = "./build"

[env.staging]
workers_dev = true
kv_namespaces = [
  { binding = "API_CACHE", id = "dae9d7aad79743bebffedf5a4976ae4f" }
]

[env.production]
routes = ["homeair.nickzylstra.com/*"]
kv_namespaces = [
  { binding = "API_CACHE", id = "f60392dd17624f36a5207eaf22f17604" }
]