compatibility_date = "2022-12-27"

name = "homeair"
account_id = "c6a05dacf1861c2fc26e676732f094d1"
main = "workers-site/index.js"

[site]
bucket = "./build"

[env.staging]
workers_dev = true

[env.production]
routes = ["homeair.nickzylstra.com/*"]
