compatibility_date = "2022-12-27"

name = "homeair"
account_id = "c6a05dacf1861c2fc26e676732f094d1"
main = "workers-site/index.ts"

[site]
bucket = "./build"

[triggers]
crons = ["* * * * *"]


[env.staging]
workers_dev = true
kv_namespaces = [
  { binding = "API_DATA", id = "ba223e765c7a49cbba472b75e4155fd9", preview_id = "acb98fa51d134b1b8c2dd85c99cced3b" }
]
# var secrets:
# - PURPLE_AIR_API_READ_KEY


[env.production]
routes = ["homeair.nickzylstra.com/*"]
kv_namespaces = [
  { binding = "API_DATA", id = "8142e14f0efd4b208d9b0a4cd23bfc5b" }
]
# var secrets:
# - PURPLE_AIR_API_READ_KEY